### ISSUE TITLE
Thanks & Meteor Package

### ISSUE THREAD

**Issue by theduke** [arhs/iban.js#17]
Hey there,

thanks for creating this library,
it is just what I needed.

I have created a wrapper package for the Meteor framework (http://meteor.com),
maybe you could add it to the README so people might find it more easily?

Can be found here: https://atmospherejs.com/theduke/iban

(Also on Github: https://github.com/theduke/meteor-iban)

Cheers.

**Comment by itoche** [comment]
Hi,

I just did it. Thanks for the work.
