### ISSUE TITLE
local account number

### ISSUE THREAD

**Issue by KirillSuhodolov** [arhs/iban.js#24]
For instance, we are using local gb account number with sort code.
How can I validate it with this library?
iban.isValidBBAN(country name + sort code + account number) not working

**Comment by itoche** [comment]
Please provide concerte example. Thanks

**Comment by KirillSuhodolov** [comment]
@itoche 
account type: GB
account number: yyyyyyy(7 digits)
SORT CODE: xx-xx-xx (6 digits)

How can we validate them?

**Comment by LaurentVB** [comment]
Hi @KirillSuhodolov , sorry for this way too long delay. Hope you found the solution in the meantime. If not, here it is:
```Javascript
iban.isValidBBAN('GB', sortCode + accountNumber);
```

Example:
```Javascript
> iban.isValidBBAN('GB', 'NWBK60161331926819')
true
```

Hope this helps.

**Comment by norothir** [comment]
Hi,

Thanks, I did made my own tweak already. I have AngularJS directive, where I do first check of illegal characters and fail, if there are non-alphanumeric characters.

I do understand your point, my use was not according your point

best regards,
      Mika
