### ISSUE TITLE
dash is not acceptable character in IBAN

### ISSUE THREAD

**Issue by norothir** [arhs/iban.js#25]
I am using iban.js to mark entered IBAN valid or invalid by using function .isValid(IBAN), I find illogical to verify IBAN valid, when you can enter non alphanumeric characters into iban. The IBAN spec does not accept non-alphanumeric charactes, so is it valid IBAN if you have them?

**Comment by LaurentVB** [comment]
That is an interesting question.

Currently, validation starts by normalizing the input, aka stripping any non-alphanumerical character. So basically, regarding validation, `BE68-5390-0754-7034` is the same as `BE68539007547034` is the same as `BE68 5390 0754 7034`.

Whether that is correct or not is a matter of perspective ;-) We chose to implement [a robust approach](https://en.wikipedia.org/wiki/Robustness_principle) by default. We still think this is the approach that gives the most benefit and we don't want to break backwards compatibility of the library.

What's possible though, is having a _strict mode_, which would be configured globally for the lib, and would validate the IBAN is a strict fashion (but then, not event spaces nor lowercase letters are allowed...)

Feel free to add a PR if you want this behavior in a future version of the lib.

Thanks for using our library.

**Comment by LaurentVB** [comment]
See https://github.com/arhs/iban.js/issues/24#issuecomment-215000265 (commented on the wrong issue)
