### ISSUE TITLE
The demo url does not work

### ISSUE THREAD

**Issue by Arkkimaagi** [arhs/iban.js#34]
The Readme.md mentions http://www.arhs-group.com/labs/iban-bban-converter/ as the address for demo. This address gives an 404 error.

**Comment by LaurentVB** [comment]
Thanks for the heads up.
@itoche Something you can fix?

**Comment by itoche** [comment]
@LaurentVB I'll do sth about this. Give me a few days.

**Comment by itoche** [comment]
Done. @LaurentVB I followed your suggestion of using Github Pages. Thanks.
