### ISSUE TITLE
BIC validation

### ISSUE THREAD

**Issue by cuhsat** [arhs/iban.js#40]
Could you possibly add the following regular expression to also validate a BIC (because mostly both fields are requested) or is that feature out of scope?

```
^([A-Z]{6}[A-Z2-9][A-NP-Z1-2])(X{3}|[A-WY-Z0-9][A-Z0-9]{2})?$
```

**Comment by LaurentVB** [comment]
Hey @cuhsat, thanks for the suggestion.
This is indeed out of scope of this library.

Laurent
