### ISSUE TITLE
IBAN.isValid ignores non-alphanumeric characters

### ISSUE THREAD

**Issue by you-fail-me** [arhs/iban.js#42]
E.g. 
```
const notValidIban = 'DE893704 0044 0532 0130 __00^#&#*#*(#';

IBAN.isValid(notValidIban); // true
```

Looks like it considers only aphanumeric characters, here I have a valid iban, but polluted with special characters, and it's still treated as valid

**Comment by LaurentVB** [comment]
Hello,
Thanks for the report.
Indeed, this is a duplicate of #35
