### ISSUE TITLE
Valid BBAN is considered invalid

### ISSUE THREAD

**Issue by abelosorio** [arhs/iban.js#48]
I have a valid BBAN but the method `isValidBBAN` returns false with it:

```javascript
iban.toBBAN('CR25010200009074883572');
// '0102 00009074883572'

iban.isValidBBAN('0102 00009074883572');
// false

iban.isValidBBAN(iban.toBBAN('CR25010200009074883572'));
// false
```

**Comment by LaurentVB** [comment]
Hello,

Sorry for the super late reply, going through the issues backlog.
The correct way to call `isValidBBAN` is by passing the country code as first parameter (which is not properly documented, I must say). So your code becomes: 

```js 
iban.isValidBBAN('CR', iban.toBBAN('CR25010200009074883572'));
// true
```

**Comment by abelosorio** [comment]
Hi @LaurentVB! It's okay.

I wouldn't close this issue until the documentation is updated, since other people may face it.

Thanks!
