### ISSUE TITLE
missing functionality like branch code, bank name etc.

### ISSUE THREAD

**Issue by yug95** [arhs/iban.js#49]
in php all functionality present like branchname, branchcode, countrycode and etc other but here no functionality other than valid. when it would be updated ?

**Comment by LaurentVB** [comment]
Hello @yug95 

Thanks for your suggestion. 
However, we currently have no plan to include that kind of feature in this library, which is solely dedicated to manipulating and validating IBANs. 
Country code could be added in a future version of the API.

Regards

Laurent
