### ISSUE TITLE
Known Vulnerability in demo boostrap version

### ISSUE THREAD

**Issue by Xtrem65** [arhs/iban.js#51]
When using npm audit : 

<project>/node_modules/iban/demo/bower_components/bootstrap/dist/js/bootstrap.js
 ↳ bootstrap 3.3.7 has known vulnerabilities: severity: medium; issue: 20184, summary: XSS in data-target attribute; https://github.com/twbs/bootstrap/issues/20184
<project>/node_modules/iban/demo/bower_components/bootstrap/dist/js/bootstrap.min.js
 ↳ bootstrap 3.3.7 has known vulnerabilities: severity: medium; issue: 20184, summary: XSS in data-target attribute; https://github.com/twbs/bootstrap/issues/20184

Can you consider upgrading the demo bootstrap to a higher, fixed version ?

**Comment by LaurentVB** [comment]
Hello @Xtrem65 

Thanks for the report. 
We don't use the vulnerable `data-target` mechanism in our demo code, so no urge to upgrade, but I'm keeping this issue around for when we update the demo.

Best regards

Laurent

**Comment by LaurentVB** [comment]
Demo has been updated and uses latest versions of used libraries (not bootstrap, btw)
