### ISSUE TITLE
Invalid IBAN number from Ivory Coast

### ISSUE THREAD

**Issue by MartijnJong** [arhs/iban.js#53]
We have a customer with an IBAN number from Ivory Coast, this number is a valid number and renderd as valid by www.iban.com 

However this libary (which we use in our software) returns that the specific IBAN number is not valid.

Note that for privacy reasons we cannot post the actual bank account number which has the issue. 

On https://www.iban.com/structure.html there is a test number with the same behaviour: CI93CI0080111301134291200589

**Comment by LaurentVB** [comment]
Hi @MartijnJong thanks for the report.

Côté d'Ivoire is not in the IBAN registry so I have trouble finding an official specification for their number. Can you provide any?
The contributor who originally added this one probably based himself on https://bank.codes/iban/structure/cote-divoire/ or some similar source. 
But indeed, from the real-life examples I can gather online, it seems to be wrong.

Will fix and release a patch soon.

Laurent

**Comment by LaurentVB** [comment]
Hey @MartijnJong , this is now fixed and published to npm as version 0.0.11
Thanks for your help 🙏
