### ISSUE TITLE
False-positive

### ISSUE THREAD

**Issue by ElleshaHackett** [arhs/iban.js#55]
The following string results in `true`:

    IT66`M0306905020100000062186

I think the character:

    `

should invalidate it. Most online validators show invalidity as well.

**Comment by zyv** [comment]
This is a duplicate of #35 - please see comments inline for a solution! @LaurentVB ok to close this?

**Comment by ElleshaHackett** [comment]
Ah, sure close it if it is a duplicate. Thing is that it should be solved.
