### ISSUE TITLE
Invalid IBAN is considered VALID

### ISSUE THREAD

**Issue by Luckino** [arhs/iban.js#58]
The number ES06 0030 1235 0903 0005 0273 is invalid
![image](https://user-images.githubusercontent.com/22609689/47799963-a2d4fe00-dd2b-11e8-8cb9-6c5b81c82eab.png)
But it is valid in your site
![image](https://user-images.githubusercontent.com/22609689/47800004-bd0edc00-dd2b-11e8-8ddd-17298e33a50c.png)

**Comment by LaurentVB** [comment]
Hi @Luckino 
Thanks for the report.
Sorry for the confusion: this library checks that the IBAN you provide is syntactically valid (the country prefix exists, the checksum is correct, the length and type of characters is compliant with the specs). 
However, this library does not check whether the bank account represented by this IBAN is valid. We don't embed the logic to make sure a bank account exists or is even a valid BBAN (domestic bank account) except for the most basic checks (length and character type)

Hope this helps
