### ISSUE TITLE
Valid IBAN is considered invalid

### ISSUE THREAD

**Issue by marcusmonteirodesouza** [arhs/iban.js#61]
According to https://www.iban.com/iban-checker the IBAN VG4835Q30660010096333091 'appears to be valid' but according to https://arhs.github.io/iban.js/ it is invalid.

**Comment by Manu1400** [comment]
According to https://www.iban.com/iban-checker the IBAN VG4835Q30660010096333091 is invalid : 

>  IBAN structure is incorrect

**Comment by MorganLebois** [comment]
According to https://www.iban.com/iban-checker the IBAN SN08SN0100152001608930008516  appears to be valid' but according to https://arhs.github.io/iban.js/ it is invalid.

**Comment by marcusmonteirodesouza** [comment]
True. I was using a fake IBAN generator, and the message 'appears to be valid' was the one that I focused on. I'll close this and perhaps talk with the generator guys.
