### ISSUE TITLE
Valid Iban is considered invalid

### ISSUE THREAD

**Issue by MorganLebois** [arhs/iban.js#62]
According to https://www.iban.com/iban-checker the IBAN SN08SN0100152001608930008516 appears to be valid' but according to https://arhs.github.io/iban.js/ it is invalid.

**Comment by Manu1400** [comment]
@MorganLebois According to https://bank.codes/iban/validate/ SN08SN0100152001608930008516 is an invalid IBAN. "The IBAN has wrong characters format. Recheck the IBAN."

The structure is https://bank.codes/iban/structure/senegal/

We can close this issue.

**Comment by LaurentVB** [comment]
Hello @MorganLebois 

Senegal is not in the official IBAN registry, so I can't be 100% sure we got this right, but according to the sources I can find ([1](https://bank.codes/iban/structure/senegal/), [2](https://en.wikipedia.org/wiki/International_Bank_Account_Number#IBAN_formats_by_country)), Senegal IBAN has the following format: 
- SN
- 2-digits check-digit
- 1 alphabetic character
- 23 digits

The IBAN you're testing is therefore invalid.
If you have an official source for a different format, I'll be glad to add it to this library.

Thanks @Manu1400 for the check 🙏
