### ISSUE TITLE
No CHANGELOG

### ISSUE THREAD

**Issue by nikwen** [arhs/iban.js#66]
Thank you very much for writing this handy module!

My only issue: When updating to new versions, there is no `CHANGELOG` file or list of changes in the releases tab on Github. When updating lots of packages at once, looking through commits for each of them is really painful.

Could you please consider adding one? Thank you very much in advance. :blush:

**Comment by LaurentVB** [comment]
Hello @nikwen 
Thanks for the suggestion. 

I just completed our release notes for all the releases since 2016 (previous ones were properly documented). See https://github.com/arhs/iban.js/releases 
Does that help ?

We'll try to keep it up to date with new releases.

**Comment by nikwen** [comment]
Thank you, Laurent! That's great. :)
