### ISSUE TITLE
[FR] HSBC bank IBAN invalid

### ISSUE THREAD

**Issue by yohannpoli** [arhs/iban.js#67]
Hi,

The "IBAN.isValid" method seems to work fine for French specification in general, but i encounter some invalid IBAN when i use the sample from [HSBC](https://www.hsbc.fr/pays-iban/).

Here the values from their spec:

France | FR | 27 | FR24 2002 0202 2606 0002 4M02 606

It seems that the iso7064Mod97_10 is not equals to 1.

Is this a normal behaviour?

Thanks in advance for your help.

**Comment by LaurentVB** [comment]
Hey Yohann, thanks for the report.
The validator on https://www.iban.com also marks this IBAN as invalid because the check digit.
I think the error is on the HSBC website... Good luck reporting a bug to them :-/

**Comment by yohannpoli** [comment]
Ok, sorry and thanks for your help @LaurentVB
