### ISSUE TITLE
SEPA countries IBAN

### ISSUE THREAD

**Issue by waqas-mehmood-pk** [arhs/iban.js#74]
This package did not support SEPA countries IBAN. I want to validate `Austria IBAN: AT61 1904 3002 3457 3201`  but its return false, not validate. I have to check all SEPA county's IBAN.

Please confirm, is it true or me something doing wrong.

Thanks

**Comment by nick-fytros** [comment]
I reports it as valid for me. I even tried `AT483200000012345864` which is listed in https://www.iban.com/structure as an Austrian IBAN and that is reports as valid too.

**Comment by LaurentVB** [comment]
Indeed, the lib support IBAN validation for all SEPA countries, and the iban you're testing comes up as valid for me on the demo page. Closing this issue as not reproducible.
